x = input('Digite algo: ')
tipo = type(x)
print('O que você digitou é do tipo: {}'.format(tipo))
print('É alfanumérico:', x.isalnum())
print('É numérico:', x.isnumeric())
print('É alfabético:', x.isalpha())
print('Seus caracteres estão na Tabela ASCII:', x.isascii())
print('Começa com letra maiúscula:', x.istitle())
print('É escrito em letra minúscula:', x.islower())
print('É escrito em letra maiúscula:', x.isupper())
print('É um dígito:', x.isdigit())
print('É decimal:', x.isdecimal())
print('É um identificador:', x.isidentifier())
print('É possível imprimir:', x.isprintable())
print('É somente espaço:', x.isspace())
