x = input('Digite algo: ')
tipo = x.__class__
print('O que você digitou é do tipo:', tipo.__name__)
print('É alfanumérico:', "Sim" if x.isalnum() else "Não")
print('É numérico:', "Sim" if x.isnumeric() else "Não")
print('É alfabético:', "Sim" if x.isalpha() else "Não")
print('Seus caracteres estão na Tabela ASCII:', "Sim" if x.isascii() else "Não")
print('Começa com letra maiúscula:', "Sim" if x.istitle() else "Não")
print('É escrito em letra minúscula:', "Sim" if x.islower() else "Não")
print('É escrito em letra maiúscula:', "Sim" if x.isupper() else "Não")
print('É um dígito:', "Sim" if x.isdigit() else "Não")
print('É decimal:', "Sim" if x.isdecimal() else "Não")
print('É um identificador:', "Sim" if x.isidentifier() else "Não")
print('É possível imprimir:', "Sim" if x.isprintable() else "Não")
print('É somente espaço:', "Sim" if x.isspace() else "Não")